// <auto-generated />
namespace Windows95.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class windows95 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(windows95));
        
        string IMigrationMetadata.Id
        {
            get { return "201905050858239_windows95"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
